CREATE TABLE IF NOT EXISTS public.monitoring (
  id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  type text,
  value text,
  user_id uuid,
  metadata jsonb
);

ALTER TABLE public.monitoring OWNER TO postgres;

ALTER TABLE public.monitoring ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.monitoring_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.monitoring
ADD CONSTRAINT monitoring_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.monitoring
ADD CONSTRAINT monitoring_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
