name: CI Fast

# Lightweight CI for quick feedback on PRs
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clone

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Type check
        run: npm run type-check
        timeout-minutes: 3

      - name: Build check
        run: npm run build
        timeout-minutes: 5
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Quick unit tests
        run: npm run test:run -- --reporter=dot
        timeout-minutes: 3
        env:
          NODE_OPTIONS: '--max-old-space-size=2048'